query GetAllTagTypes {
  allTagTypes {
    id
    label
    tags {
      id
      label
    }
  }
}

mutation AddTagTypes {
  addCategory: addTagType(label: "Category") {
    success
    message
    tagType {
      id
      label
      tags {
        id
        label
      }
    }
  }
  addCuisine: addTagType(label: "Cuisine") {
    success
    message
    tagType {
      id
      label
      tags {
        id
        label
      }
    }
  }
  addEquipment: addTagType(label: "Equipment") {
    success
    message
    tagType {
      id
      label
      tags {
        id
        label
      }
    }
  }
  addMealType: addTagType(label: "Meal Type") {
    success
    message
    tagType {
      id
      label
      tags {
        id
        label
      }
    }
  }
}

mutation UpdateTagType {
  updateTagType(id: "2", label: "Cuisine") {
    success
    message
    tagType {
      id
      label
      tags {
        id
        label
      }
    }
  }
}

mutation DeleteTagType {
  deleteTagType(id: "6") {
    success
    message
    tagType {
      id
      label
      tags {
        id
        label
      }
    }
  }
}
